import React from 'react';
import * as S from '../styled/NoticeStyled/NoticeStyle';

const NoticeContainer = () => {
    return (
        <>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
            <S.Container>
                <S.ContainerContant>
                    <S.ContainerTitle>
                        제목
                    </S.ContainerTitle>
                    <S.ContainerDay>
                        2020.11.03
                    </S.ContainerDay>
                </S.ContainerContant>
            </S.Container>
        </>
    )
}

export default NoticeContainer;